version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17.0  # Use a stable Node.js image
    working_directory: ~/project

jobs:
  install-deps:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

  build-project:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build Astro project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy:
    executor: node-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Netlify (example)
          command: |
            npm install -g netlify-cli
            netlify deploy --dir=dist --prod --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install-deps
      - build-project:
          requires:
            - install-deps
      - deploy:
          requires:
            - build-project
