version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.5.1
    working_directory: ~/project

jobs:
  install-dependencies:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: node-modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  lint:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run ESLint
          command: npm run lint

  type-check:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run TypeScript type check
          command: npm run type-check

  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: npm test -- --coverage
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage

  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Build React app
          command: npm run build
      - store_artifacts:
          path: build

workflows:
  build-and-test:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - type-check:
          requires:
            - install-dependencies
      - test:
          requires:
            - install-dependencies
      - build:
          requires:
            - test
