version: 2.1

jobs:
  # Node.js / Vuex build & test
  node-build:
    docker:
      - image: cimg/node:18.20
      - image: cimg/php:8.2-node

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installer dépendances Node
          command: npm install
      - run:
          name: Tests Node.js
          command: npm test
      - run:
          name: Build Vuex
          command: npm run build

  # PHP / Composer build & test
  php-build:
    docker:
      - image: cimg/php:8.2-node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installer dépendances Composer
          command: composer install --no-interaction --prefer-dist
      - run:
          name: Tests PHP
          command: composer test

  # Déploiement vers Vercel
  deploy:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout
      - run:
          name: Déploiement Vercel
          command: npx vercel --prod --token $VERCEL_TOKEN --confirm

workflows:

  build_and_deploy:
    jobs:
      - node-build
      - php-build
      - deploy:
          context: moneyphone-prod
          requires:
            - node-build
            - php-build
          filters:
            branches:
              only: project-setup
