version: 2.1

executors:
  php-executor:
    docker:
      - image: cimg/php:8.2-node # Node inclus pour installer Vercel CLI
    working_directory: ~/repo

jobs:
  build:
    executor: php-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: composer install
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    executor: php-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run PHP tests
          command: ./vendor/bin/phpunit --configuration phpunit.xml

  deploy_vercel:
    executor: php-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Vercel
          command: |
            sudo npm install -g vercel
            # Déploiement en production sans interaction
            vercel --token $VERCEL_TOKEN --prod --yes

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy_vercel:
          requires:
            - test
          filters:
            branches:
              only: main
